version: '3.9'

services:
  db:
    container_name: arbif-mysql
    image: mysql:8.0.17
    restart: always
    init: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_arbif
    ports:
      - "3306:3306"